### ISSUE TITLE
icc compilation fails

### ISSUE THREAD

**Issue by seallard** [seallard/cnF2freq#9]
When compiling with icc (19.1.1.217 20200306):
```bash
icc cnF2freq.cpp -std=c++17 -L /home/seal/Downloads/boost_1_70_0/stage/lib -I /home/seal/Downloads/boost_1_70_0 -qopenmp -qopenmp-linkstatic -fast -ftz -o cnF2freq
```

The compiler fails with the following errors:
```bash
cnF2freq.cpp(6194): error: "auto" is not allowed here
  	sampleInds, auto indexconv, double unit)
  	            ^

cnF2freq.cpp(6213): error: "auto" is not allowed here
  	sampleInds, auto dohaploweight, auto indexconv)
  	            ^

cnF2freq.cpp(6213): error: "auto" is not allowed here
  	sampleInds, auto dohaploweight, auto indexconv)
  	                                ^

cnF2freq.cpp(6252): error: "auto" is not allowed here
  		   const vector<individ*>& sampleInds, double unit, double genounit, auto dohaploweight, auto indexconv)
  		                                                                     ^

cnF2freq.cpp(6252): error: "auto" is not allowed here
  		   const vector<individ*>& sampleInds, double unit, double genounit, auto dohaploweight, auto indexconv)
  		                                                                                         ^

cnF2freq.cpp(6352): error: "auto" is not allowed here
  double initPadding(const vector<individ*>& sampleInds, int count, auto dohaploweight)                                                                 ^
```
However, the program does compile with g++ (7.5.0) and just gives warnings for the errors above.

**Comment by seallard** [comment]
Example of g++ warning: 
```bash
cnF2freq.cpp:6194:14: warning: ISO C++ forbids use of ‘auto’ in parameter declaration [-Wpedantic]
  sampleInds, auto indexconv, double unit)
              ^~~~
```
